---
name: CI
on:
  push:
    branches:
      - main
    paths:
      - app/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      
      - name: Build
        run: pio run
